In [1]:
import pandas as pd
from collections import Counter

In [4]:
# load data exported with Workshops3DOFDataPreparation.ipynb
df = pd.read_csv('ImagesDifference/diff_pixels.csv')
df

,Unnamed: 0,list idx,first image,second image,diff pixels,same size
0,0,715,screenshot-2019101-123153-12.png,screenshot-2019101-123154-12.png,0,True
1,1,716,screenshot-2019101-123154-12.png,screenshot-2019101-123155-12.png,0,True
2,2,717,screenshot-2019101-123155-12.png,screenshot-2019101-123156-12.png,0,True
3,3,718,screenshot-2019101-123156-12.png,screenshot-2019101-123157-12.png,0,True
4,4,719,screenshot-2019101-123157-12.png,screenshot-2019101-123158-12.png,0,True
...,...,...,...,...,...,...
33451,33451,34170,screenshot-20191015-191133-25.png,screenshot-20191015-191134-25.png,524,True
33452,33452,34171,screenshot-20191015-191134-25.png,screenshot-20191015-191135-25.png,3,True
33453,33453,34172,screenshot-20191015-191135-25.png,screenshot-20191015-191136-25.png,2,True
33454,33454,34173,screenshot-20191015-191136-25.png,screenshot-20191015-191137-25.png,2,True
33455,33455,34174,screenshot-20191015-191137-25.png,screenshot-20191015-191138-25.png,3,True

In [5]:
df.rename(columns={'Unnamed: 0':'idx'}, inplace=True)
df['user'] = 0
df

,idx,list idx,first image,second image,diff pixels,same size,user
0,0,715,screenshot-2019101-123153-12.png,screenshot-2019101-123154-12.png,0,True,0
1,1,716,screenshot-2019101-123154-12.png,screenshot-2019101-123155-12.png,0,True,0
2,2,717,screenshot-2019101-123155-12.png,screenshot-2019101-123156-12.png,0,True,0
3,3,718,screenshot-2019101-123156-12.png,screenshot-2019101-123157-12.png,0,True,0
4,4,719,screenshot-2019101-123157-12.png,screenshot-2019101-123158-12.png,0,True,0
...,...,...,...,...,...,...,...
33451,33451,34170,screenshot-20191015-191133-25.png,screenshot-20191015-191134-25.png,524,True,0
33452,33452,34171,screenshot-20191015-191134-25.png,screenshot-20191015-191135-25.png,3,True,0
33453,33453,34172,screenshot-20191015-191135-25.png,screenshot-20191015-191136-25.png,2,True,0
33454,33454,34173,screenshot-20191015-191136-25.png,screenshot-20191015-191137-25.png,2,True,0
33455,33455,34174,screenshot-20191015-191137-25.png,screenshot-20191015-191138-25.png,3,True,0

In [6]:
df_all_movement = df[df['diff pixels'] != 0]
df_all_movement

,idx,list idx,first image,second image,diff pixels,same size,user
31,31,746,screenshot-2019101-123225-12.png,screenshot-2019101-123226-12.png,1,True,0
41,41,756,screenshot-2019101-123236-12.png,screenshot-2019101-123237-12.png,5,True,0
42,42,757,screenshot-2019101-123237-12.png,screenshot-2019101-123238-12.png,5,True,0
111,111,826,screenshot-2019101-123350-12.png,screenshot-2019101-123351-12.png,38558,True,0
112,112,827,screenshot-2019101-123351-12.png,screenshot-2019101-123352-12.png,30634,True,0
...,...,...,...,...,...,...,...
33451,33451,34170,screenshot-20191015-191133-25.png,screenshot-20191015-191134-25.png,524,True,0
33452,33452,34171,screenshot-20191015-191134-25.png,screenshot-20191015-191135-25.png,3,True,0
33453,33453,34172,screenshot-20191015-191135-25.png,screenshot-20191015-191136-25.png,2,True,0
33454,33454,34173,screenshot-20191015-191136-25.png,screenshot-20191015-191137-25.png,2,True,0
33455,33455,34174,screenshot-20191015-191137-25.png,screenshot-20191015-191138-25.png,3,True,0

In [7]:
df_strong_movement = df_all_movement[df_all_movement['diff pixels'] > 2000]
df_strong_movement

,idx,list idx,first image,second image,diff pixels,same size,user
111,111,826,screenshot-2019101-123350-12.png,screenshot-2019101-123351-12.png,38558,True,0
112,112,827,screenshot-2019101-123351-12.png,screenshot-2019101-123352-12.png,30634,True,0
113,113,828,screenshot-2019101-123352-12.png,screenshot-2019101-123353-12.png,24070,True,0
114,114,829,screenshot-2019101-123353-12.png,screenshot-2019101-123354-12.png,15548,True,0
115,115,830,screenshot-2019101-123354-12.png,screenshot-2019101-123355-12.png,19247,True,0
...,...,...,...,...,...,...,...
33339,33339,34058,screenshot-20191015-19940-25.png,screenshot-20191015-19941-25.png,4987,True,0
33340,33340,34059,screenshot-20191015-19941-25.png,screenshot-20191015-19942-25.png,4096,True,0
33341,33341,34060,screenshot-20191015-19942-25.png,screenshot-20191015-19943-25.png,3177,True,0
33342,33342,34061,screenshot-20191015-19943-25.png,screenshot-20191015-19944-25.png,2888,True,0
33436,33436,34155,screenshot-20191015-191118-25.png,screenshot-20191015-191119-25.png,22911,True,0

In [18]:
user = 1
for row in range(len(df_strong_movement)-1):
    if df_strong_movement.iloc[row+1, 1] - df_strong_movement.iloc[row, 1] > 2:
        user += 1
    df_strong_movement.iloc[row, 6] = user
    df_strong_movement.iloc[row+1, 6] = user

In [19]:
users = Counter(df_strong_movement['user'])
users

Counter({1: 820,
         2: 103,
         3: 1,
         4: 1,
         5: 5,
         6: 709,
         7: 4,
         8: 1,
         9: 4,
         10: 84,
         11: 1,
         12: 1,
         13: 1,
         14: 3,
         15: 2,
         16: 1,
         17: 3,
         18: 2,
         19: 4,
         20: 19,
         21: 2,
         22: 2,
         23: 3,
         24: 1,
         25: 5,
         26: 2,
         27: 7,
         28: 1,
         29: 31,
         30: 72,
         31: 1,
         32: 1,
         33: 2,
         34: 1,
         35: 6,
         36: 1275,
         37: 181,
         38: 139,
         39: 85,
         40: 1,
         41: 2,
         42: 1,
         43: 1,
         44: 14,
         45: 37,
         46: 3,
         47: 3,
         48: 30,
         49: 4,
         50: 31,
         51: 1,
         52: 7,
         53: 4,
         54: 3,
         55: 1,
         56: 1,
         57: 4,
         58: 1,
         59: 150,
         60: 1,
         61: 1,
         62: 1,
         63: 3,
         64: 1,
         65: 1,
         66: 119,
         67: 4,
         68: 1,
         69: 1,
         70: 2,
         71: 45,
         72: 1,
         73: 136,
         74: 3,
         75: 6,
         76: 169,
         77: 1,
         78: 1,
         79: 1,
         80: 1,
         81: 1,
         82: 1,
         83: 2,
         84: 3,
         85: 6,
         86: 27,
         87: 1,
         88: 16,
         89: 243,
         90: 11,
         91: 54,
         92: 1,
         93: 3,
         94: 1,
         95: 3,
         96: 1,
         97: 4,
         98: 191,
         99: 4,
         100: 9,
         101: 4,
         102: 3,
         103: 1,
         104: 32,
         105: 1,
         106: 19,
         107: 1,
         108: 2,
         109: 2,
         110: 19,
         111: 1,
         112: 1,
         113: 2,
         114: 2,
         115: 1,
         116: 2,
         117: 16,
         118: 1,
         119: 2,
         120: 1,
         121: 236,
         122: 2,
         123: 1,
         124: 1,
         125: 1,
         126: 45,
         127: 14,
         128: 22,
         129: 6,
         130: 5,
         131: 175,
         132: 1,
         133: 29,
         134: 1,
         135: 2,
         136: 7,
         137: 1,
         138: 3,
         139: 27,
         140: 73,
         141: 9,
         142: 2,
         143: 1,
         144: 12,
         145: 29,
         146: 48,
         147: 6,
         148: 1,
         149: 3,
         150: 1,
         151: 1,
         152: 4,
         153: 1,
         154: 12,
         155: 1,
         156: 31,
         157: 1,
         158: 4,
         159: 8,
         160: 2,
         161: 5,
         162: 2,
         163: 1,
         164: 1,
         165: 139,
         166: 6,
         167: 56,
         168: 147,
         169: 10,
         170: 28,
         171: 3,
         172: 42,
         173: 41,
         174: 77,
         175: 3,
         176: 2,
         177: 32,
         178: 2,
         179: 3,
         180: 23,
         181: 6,
         182: 5,
         183: 1,
         184: 31,
         185: 2})

In [20]:
df_strong_movement

,idx,list idx,first image,second image,diff pixels,same size,user
111,111,826,screenshot-2019101-123350-12.png,screenshot-2019101-123351-12.png,1,1,1
112,112,827,screenshot-2019101-123351-12.png,screenshot-2019101-123352-12.png,1,1,1
113,113,828,screenshot-2019101-123352-12.png,screenshot-2019101-123353-12.png,1,1,1
114,114,829,screenshot-2019101-123353-12.png,screenshot-2019101-123354-12.png,1,1,1
115,115,830,screenshot-2019101-123354-12.png,screenshot-2019101-123355-12.png,1,1,1
...,...,...,...,...,...,...,...
33339,33339,34058,screenshot-20191015-19940-25.png,screenshot-20191015-19941-25.png,184,184,184
33340,33340,34059,screenshot-20191015-19941-25.png,screenshot-20191015-19942-25.png,184,184,184
33341,33341,34060,screenshot-20191015-19942-25.png,screenshot-20191015-19943-25.png,184,184,184
33342,33342,34061,screenshot-20191015-19943-25.png,screenshot-20191015-19944-25.png,185,185,185
33436,33436,34155,screenshot-20191015-191118-25.png,screenshot-20191015-191119-25.png,185,185,185

In [21]:
min_30_seconds_users = []
for user in range(len(users)):
    if users[user+1] > 30:
        min_30_seconds_users.append(user+1)

In [22]:
df_min_30_seconds_strong_movement = df_strong_movement[df_strong_movement['user'].isin(min_30_seconds_users)]

In [23]:
df_min_30_seconds_strong_movement

,idx,list idx,first image,second image,diff pixels,same size,user
111,111,826,screenshot-2019101-123350-12.png,screenshot-2019101-123351-12.png,1,1,1
112,112,827,screenshot-2019101-123351-12.png,screenshot-2019101-123352-12.png,1,1,1
113,113,828,screenshot-2019101-123352-12.png,screenshot-2019101-123353-12.png,1,1,1
114,114,829,screenshot-2019101-123353-12.png,screenshot-2019101-123354-12.png,1,1,1
115,115,830,screenshot-2019101-123354-12.png,screenshot-2019101-123355-12.png,1,1,1
...,...,...,...,...,...,...,...
33337,33337,34056,screenshot-20191015-19938-25.png,screenshot-20191015-19939-25.png,184,184,184
33338,33338,34057,screenshot-20191015-19939-25.png,screenshot-20191015-19940-25.png,184,184,184
33339,33339,34058,screenshot-20191015-19940-25.png,screenshot-20191015-19941-25.png,184,184,184
33340,33340,34059,screenshot-20191015-19941-25.png,screenshot-20191015-19942-25.png,184,184,184
33341,33341,34060,screenshot-20191015-19942-25.png,screenshot-20191015-19943-25.png,184,184,184

In [24]:
min_30_sec_users = Counter(df_min_30_seconds_strong_movement['user'])

In [26]:
df_first_last = pd.DataFrame(columns={'first', 'last', 'number'})
for user in min_30_seconds_users:
    df_temp = df_min_30_seconds_strong_movement[df_min_30_seconds_strong_movement['user'] == user]
    new_row = {'first':df_temp.iloc[0, 2], 'last':df_temp.iloc[-1, 3], 'number':min_30_sec_users[user]}
    df_first_last = df_first_last.append(new_row, ignore_index=True)
df_first_last

,first,number,last
0,screenshot-2019101-123350-12.png,820,screenshot-2019101-12529-12.png
1,screenshot-2019101-125210-12.png,103,screenshot-2019101-125457-12.png
2,screenshot-2019101-18337-13.png,709,screenshot-2019101-19357-15.png
3,screenshot-2019101-191426-15.png,84,screenshot-2019107-104416-16.png
4,screenshot-2019107-11558-16.png,31,screenshot-2019107-11596-16.png
5,screenshot-2019107-11596-16.png,72,screenshot-2019107-12458-16.png
6,screenshot-2019107-1263-16.png,1275,screenshot-2019107-12294-16.png
7,screenshot-2019107-12294-16.png,181,screenshot-2019107-123246-16.png
8,screenshot-2019107-123246-16.png,139,screenshot-2019107-123555-16.png
9,screenshot-2019107-123555-16.png,85,screenshot-2019107-163150-17.png
10,screenshot-2019107-181936-18.png,37,screenshot-2019107-184346-18.png
11,screenshot-2019107-185217-18.png,31,screenshot-2019107-185253-18.png
12,screenshot-2019107-18584-18.png,150,screenshot-2019107-19159-18.png
13,screenshot-2019107-19511-18.png,119,screenshot-2019107-19718-18.png
14,screenshot-2019107-19818-18.png,45,screenshot-2019107-19910-18.png
15,screenshot-2019107-19913-18.png,136,screenshot-2019107-191139-18.png
16,screenshot-2019107-192729-18.png,169,screenshot-2019107-193127-18.png
17,screenshot-20191015-11956-21.png,243,screenshot-20191015-111412-21.png
18,screenshot-20191015-111437-21.png,54,screenshot-20191015-111638-21.png
19,screenshot-20191015-112043-21.png,191,screenshot-20191015-112453-21.png
20,screenshot-20191015-112930-21.png,32,screenshot-20191015-113253-21.png
21,screenshot-20191015-122642-22.png,236,screenshot-20191015-123150-22.png
22,screenshot-20191015-123528-22.png,45,screenshot-20191015-123728-22.png
23,screenshot-20191015-12410-22.png,175,screenshot-20191015-124418-22.png
24,screenshot-20191015-163750-24.png,73,screenshot-20191015-164025-24.png
25,screenshot-20191015-181816-25.png,48,screenshot-20191015-181911-25.png
26,screenshot-20191015-183955-25.png,31,screenshot-20191015-184035-25.png
27,screenshot-20191015-184430-25.png,139,screenshot-20191015-18470-25.png
28,screenshot-20191015-184710-25.png,56,screenshot-20191015-184849-25.png
29,screenshot-20191015-184849-25.png,147,screenshot-20191015-185129-25.png
30,screenshot-20191015-185528-25.png,42,screenshot-20191015-185615-25.png
31,screenshot-20191015-185615-25.png,41,screenshot-20191015-185830-25.png
32,screenshot-20191015-185830-25.png,77,screenshot-20191015-19015-25.png
33,screenshot-20191015-19034-25.png,32,screenshot-20191015-19129-25.png
34,screenshot-20191015-1984-25.png,31,screenshot-20191015-19943-25.png